files:
  - source: /translation/source/messages.properties
    translation: /translation/dest/messages_%two_letters_code%.properties
    translate_attributes: 0
    update_option: update_without_changes
commit_message: 'New translations: %original_file_name% (%language%)'
append_commit_message: false

